export const colorPalette = {
  white: '#f0f0f0',
  black: '#000000',
  swedish_pallet_black_pearl: '#1e272e',
  swedish_pallet_megaman: '#4bcffa',
  swedish_pallet_sunset_orange: '#ff5e57',
  swedish_pallet_london_square: '#808e9b',
  swedish_pallet_iriel_yellow: '#ffdd59',
  swedish_pallet_good_n: '#485460',
  swedish_pallet_dark_periwinkle: '#575fcf',
  swedish_pallet_free_speech_blue: '#3c40c6',
  spanish_pallet_lucky_point: '#2c2c54',
  indian_pallet_fiery_fuchsia: '#B33771',
  indian_pallet_magenta_purple: '#6D214F',
  indian_pallet_falling: '#CAD3C8',
  indian_pallet_ships_off: '#2C3A47',
  indian_pallet_navy_blue: '#182C61',
  indian_pallet_white_pepper: '#F8EFBA',
};
